name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 172.167.64.218 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh ubuntu@172.167.64.218 << 'EOF'
          cd /home/ubuntu

          git pull origin main
          
          cd frontend
          npm install
          npm run build
          pm2 restart frontend

          cd ../backend
          pip3 install -r install.txt
          pm2 restart backend
        EOF
